[features]
seeds = false
[programs.localnet]
calcdapp = "FMemW4dzibupLEQ425MuHU6gzoZxpHEMNDVW63GaaVyX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dontaskit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
